accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'


urlpatterns = [
    # user account
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate/<str:username>/<str:token>/', views.activate_account_view, name='activate'),
    path('password_change/<str:username>/', views.change_password_view, name='password_change'),
    # user profile
    path('profile/create/', views.profile_create_view, name='profile_create'),
    path('profile/<str:username>/detail/', views.profile_detail_view, name='profile_detail'),
    path('profile/<str:username>/update/', views.profile_update_view, name='profile_update'),
    # user follow system
    path('profile/follow/<str:username>/', views.user_follow_view, name='follow_user'),
    path('profile/unfollow/<str:username>/', views.user_unfollow_view, name='unfollow_user'),
    path('profile/<str:username>/followers/', views.user_followers_view, name='followers'),
    path('profile/<str:username>/following/', views.user_following_view, name='following')
]

api/urls.py
from django.urls import path

from api.views import movies_views, accounts_views, posts_views

app_name = 'api'


urlpatterns = [
    # movies
    path('movies/movies/', movies_views.MovieListAPIView.as_view(), name='movies_list'),
    path('accounts/create/', accounts_views.UserCreateAPIView.as_view(), name='register'),
    path('accounts/activate/', accounts_views.ActivateUserAPIView.as_view(),name='activate'),
    path('posts/posts/', posts_views.PostsListAPIView.as_view(), name='posts_list'),
    path('posts/posts/<str:slug>/', posts_views.PostAPIView.as_view(), name='posts')
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'


urlpatterns = [
    path('', views.post_list_view, name='post_list'),
    path('post/<slug:post_slug>/', views.post_detail_view, name='post_detail'),
    path('post/<int:post_id>/like/', views.post_like_view, name='post_like'),
    path('post/<slug:slug>/comment/', views.post_comment_view, name='post_comment'),
    path('post/<int:post_id>/dislike/', views.post_dislike_view, name='post_dislike'),
    path('post/comment/<int:comment_id>/like/', views.comment_like_view, name='comment_like'),
    path('post/comment/<int:comment_id>/dislike/', views.comment_dislike_view, name='comment_dislike'),
    path('post/comment/disabling/<int:comment_id>/', views.comment_disable_view, name='comment_disabling'),
    path('post/comment/delete/<int:comment_id>', views.comment_delete_view, name='comment_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api/v1.0/', include('api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('weather/', include('weather.urls', namespace='weather')),
    path('', include('blog.urls', namespace='blog')),
]

weather/urls.py
from django.urls import path

from weather import views

app_name = 'weather'


urlpatterns = [
    path('today/', views.WeatherCityView.as_view(), name='today'),
    path('user-city/create/', views.UserCityCreateView.as_view(), name='user_city_create')
]

templates/base/nav/_footer.html
<footer class="py-3 my-4 mt-auto">
  <hr>
  <p class="text-center text-muted">© 2021 Company, Inc</p>
</footer>

templates/base/nav/_header.html
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:post_list' %}" class="nav-link px-2 text-secondary">Home</a></li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-white" href="#" id="weatherDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Weather
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="weatherDropdown">
                    <li>
                      <a class="dropdown-item" href="{% url 'weather:today' %}">
                        Current weather
                      </a>
                    </li>
                  </ul>
                </li>
              </ul> 

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
      </form>

      <div class="text-end">
        {% if request.user.is_authenticated %}
          <a class="text-decoration-none text-white me-3"
             href="{% url 'accounts:profile_detail' username=request.user %}">
          {% if request.user.profile %}
            <img src="{{ request.user.profile.avatar }}" alt="" width="25" height="25">
          {% endif %}
          <span>{{ request.user }}</span>
          </a>

          <a href="{% url 'accounts:logout' %}">
            <button type="button" class="btn btn-warning">Logout</button>
          </a>
        {% else %}
          <a href="{% url 'accounts:login' %}" type="button" class="btn btn-outline-light me-2">Login</a>
          <a href="{% url 'accounts:register' %}" type="button" class="btn btn-warning">Sign-up</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>