accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'


urlpatterns = [
    # user account
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate/<str:username>/<str:token>/', views.activate_account_view, name='activate'),
    path('password_change/<str:username>/', views.change_password_view, name='password_change'),
    # user profile
    path('profile/create/', views.profile_create_view, name='profile_create'),
    path('profile/<str:username>/detail/', views.profile_detail_view, name='profile_detail'),
    path('profile/<str:username>/update/', views.profile_update_view, name='profile_update'),
    # user follow system
    path('profile/follow/<str:username>/', views.user_follow_view, name='follow_user'),
    path('profile/unfollow/<str:username>/', views.user_unfollow_view, name='unfollow_user'),
    path('profile/<str:username>/followers/', views.user_followers_view, name='followers'),
    path('profile/<str:username>/following/', views.user_following_view, name='following')
]

api/urls.py
from django.urls import path

from api.views import movies_views, accounts_views, posts_views

app_name = 'api'


urlpatterns = [
    # movies
    path('movies/movies/', movies_views.MovieListAPIView.as_view(), name='movies_list'),
    path('accounts/create/', accounts_views.UserCreateAPIView.as_view(), name='register'),
    path('accounts/activate/', accounts_views.ActivateUserAPIView.as_view(),name='activate'),
    path('posts/posts/', posts_views.PostsListAPIView.as_view(), name='posts_list'),
    path('posts/posts/<str:slug>/', posts_views.PostAPIView.as_view(), name='posts')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api/v1.0/', include('api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('weather/', include('weather.urls', namespace='weather')),
    path('', include('blog.urls', namespace='blog')),
]

accounts/models.py
import hashlib

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.crypto import get_random_string
from django.utils import timezone

from accounts.managers import UserManager
from accounts.validators import (
    validate_username,
    validate_name,
    validate_birth_date
)


class User(AbstractUser):
    username = models.CharField(max_length=50,
                                unique=True,
                                validators=[validate_username])
    email = models.EmailField(unique=True,
                              max_length=255)
    first_name = models.CharField(max_length=50,
                                  validators=[validate_name])
    last_name = models.CharField(max_length=50,
                                 validators=[validate_name])

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        self.first_name = self.first_name.capitalize()
        self.last_name = self.last_name.capitalize()
        self.username = self.username.lower()
        super().save(*args, **kwargs)


class Profile(models.Model):
    GENDER_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.URLField(max_length=255, blank=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    date_of_birth = models.DateField(validators=[validate_birth_date])
    bio = models.TextField()
    info = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.user} \'s profile'

    def create_gravatar(self):
        md5_hash = hashlib.md5(self.user.email.encode('utf-8')).hexdigest()
        gravatar_url = f'https://www.gravatar.com/avatar/{md5_hash}?d=identicon&s={200}'
        self.avatar = gravatar_url

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
        if not self.avatar:
            self.create_gravatar()
        super().save(*args, **kwargs)


class AbstractToken(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=32, default='', unique=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.pk:
            self.token = get_random_string(length=32)
        super().save(*args, **kwargs)

    def verify_token(self):
        return self.created >= timezone.now() - timezone.timedelta(days=1)


class ActivateToken(AbstractToken):
    def __str__(self):
        return f'{self.user}\'s activate token'

    class Meta:
        verbose_name_plural = 'Activation Tokens'


class PasswordResetToken(AbstractToken):
    def __str__(self):
        return f'{self.user}\'s password reset token'

    class Meta:
        verbose_name_plural = 'Password Reset Tokens'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile

User = get_user_model()


class DateInputCustom(forms.DateInput):
    input_type = 'date'


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    remember_me = forms.BooleanField(
        required=False,
        initial=True,
        widget=forms.CheckboxInput()
    )


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(),
            'email': forms.EmailInput(),
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['gender', 'date_of_birth', 'avatar', 'bio', 'info']

        labels = {
            'date_of_birth': 'Date of your Birth',
            'avatar': 'Avatar URL'
        }

        placeholders = {
            'avatar': 'Left empty to use gravatar',
            'bio': 'Write a short biography',
            'info': 'Enter some additional information'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'placeholder': self.Meta.placeholders.get(field_name, '')
            })
        self.fields['date_of_birth'].widget = DateInputCustom()

accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_http_methods
from django.conf import settings

from accounts import forms
from accounts import models
from blog.models import Post, Follow
from accounts.utils import send_activation_email

User = get_user_model()


@require_http_methods(["GET", "POST"])
def register_view(request):
    if request.user.is_authenticated:
        messages.info(request, 'You are already register.')
        return redirect('blog:post_list')

    if request.method == 'POST':
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user_token = models.ActivateToken.objects.create(user=user)
            send_activation_email(user, user_token, settings.EMAIL_HOST_USER, request)
            return redirect('accounts:login')
        return render(request, 'accounts/register.html', {'form': form})

    form = forms.RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


@require_http_methods(["GET"])
def activate_account_view(request, username, token):
    user = get_object_or_404(User, username=username)
    token = get_object_or_404(models.ActivateToken, token=token, user=user)

    if user.is_active:
        messages.error(request, 'User is already activated.')
        return redirect('blog:post_list')

    if token.verify_token():
        user.is_active = True
        token.delete()
        user.save()

        messages.success(request, 'Activation complete.')
        return redirect('accounts:login')

    messages.error(request, 'Token expired')
    return redirect('accounts:test')


@require_http_methods(["GET", "POST"])
def login_view(request):
    if request.user.is_authenticated:
        messages.info(request, 'You are already logged in.')
        return redirect('blog:post_list')

    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            remember_me = form.cleaned_data.get('remember_me')

            user = authenticate(request, email=email, password=password)

            if not remember_me:
                request.session.set_expiry(0)
            else:
                request.session.set_expiry(60 * 60 * 24 * 7)

            if user:
                login(request, user)
                next_url = request.GET.get('next', 'blog:post_list')
                return redirect(next_url)
            else:
                messages.error(request, 'Invalid email or password')
                return redirect('accounts:login')
        else:
            messages.error(request, 'Invalid form data')
            return render(request, 'accounts/login.html', {'form': form})

    form = forms.LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


@require_http_methods(["GET"])
@login_required
def logout_view(request):
    logout(request)
    return redirect('accounts:login')


@require_http_methods(["GET", "POST"])
@login_required
def change_password_view(request, username):
    user = get_object_or_404(User, username=username)

    if request.user != user:
        messages.error(request, f'You don\'t have permission to change password for user {username}')
        return redirect('accounts:profile_detail', username=username)

    if request.method == 'POST':
        form = PasswordChangeForm(user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)

            messages.success(request, 'Your password was successfully updated.')
            return redirect('accounts:profile_detail', username=username)
        else:
            return render(request, 'accounts/change_password.html', {'form': form})

    form = PasswordChangeForm(user)
    return render(request, 'accounts/change_password.html', {'form': form})


@require_http_methods(["GET", "POST"])
@login_required
def profile_create_view(request):
    if hasattr(request.user, 'profile'):
        messages.info(request, 'You already have profile')
        return redirect('blog:post_list')

    if request.method == 'POST':
        form = forms.ProfileForm(request.POST)

        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()

            return redirect('blog:post_list')
        else:
            return render(request, 'accounts/profile/profile_create.html', {'form': form})

    form = forms.ProfileForm()
    return render(request, 'accounts/profile/profile_create.html', {'form': form})


@require_http_methods(["GET"])
def profile_detail_view(request, username):
    profile = get_object_or_404(models.Profile, user__username=username)
    posts = Post.published.filter(author=profile.user)[:4]
    context = {
        'profile': profile,
        'posts': posts
    }
    return render(request, 'accounts/profile/profile_detail.html', context)


@require_http_methods(["GET", "POST"])
@login_required
def profile_update_view(request, username):
    profile = get_object_or_404(models.Profile, user__username=username)

    if request.user != profile.user:
        messages.error(request, 'You don\'t have permission to edit this profile.')
        return redirect('accounts:profile_detail', username=username)

    if request.method == 'POST':
        form = forms.ProfileForm(instance=profile, data=request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Profile updated')
            return redirect('accounts:profile_detail', username=username)
        else:
            return render(request, 'accounts/profile/profile_update.html', {'form': form})

    form = forms.ProfileForm(instance=profile)
    return render(request, 'accounts/profile/profile_update.html', {'form': form})


@login_required
def user_follow_view(request, username):
    user = get_object_or_404(User, username=username)
    follow = Follow(follower=request.user, followed=user)
    follow.save()
    messages.success(request, f'For now you follow {user.get_full_name()}')
    return redirect('accounts:profile_detail', username=username)


@login_required
def user_unfollow_view(request, username):
    user = get_object_or_404(User, username=username)
    existing_follow = Follow.objects.filter(follower=request.user, followed=user).first()
    if existing_follow:
        existing_follow.delete()
        messages.success(request, f'You have unfollowed {user.get_full_name()}')
    else:
        messages.warning(request, f'You are not following {user.get_full_name()}')
    return redirect('accounts:profile_detail', username=username)


def user_followers_view(request, username):
    user = get_object_or_404(User, username=username)
    followers = user.followers.filter(followed=user.id)
    return render(request, 'accounts/profile/followers.html', {'user': user,
                                                               'followers': followers})


def user_following_view(request, username):
    user = get_object_or_404(User, username=username)
    followings = user.following.filter(follower=user.id)
    return render(request, 'accounts/profile/followed.html', {'user': user,
                                                              'followings': followings})

api/views/accounts_views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.generics import get_object_or_404

from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView


from api.serializers.accounts_serializers import UserCreateSerializer, ActivateUserSerializer
from api.utils import send_activation_api_email
from config import settings

from accounts.models import ActivateToken

User = get_user_model()


class UserCreateAPIView(APIView):
    def post(self, request: Request) -> Response:
        create_serializer = UserCreateSerializer(data=request.data)
        if create_serializer.is_valid():
            user = create_serializer.save()
            user_token = ActivateToken.objects.create(user=user)
            send_activation_api_email(user, user_token, settings.EMAIL_HOST_USER)
            return Response({'message': 'User created successfully. Activation email sent.'},
                                status=status.HTTP_201_CREATED)
        return Response(create_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ActivateUserAPIView(APIView):
    def post(self, request: Request) -> Response:
        activate_serializer = ActivateUserSerializer(data=request.data)
        if activate_serializer.is_valid():
            email = activate_serializer.validated_data['email']
            token = activate_serializer.validated_data['token']

            user = get_object_or_404(User, email=email)
            if user.is_active:
                return Response({'message': 'User is already activated.'})

            activate_token = get_object_or_404(ActivateToken, user=user, token=token)

            if activate_token.verify_token():
                user.is_active = True
                activate_token.delete()
                user.save()

            return Response({'detail': 'User activated successfully.'}, status=status.HTTP_200_OK)
        return Response(activate_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/accounts/profile/followed.html
{% extends 'base/_base.html' %}

{% block title %}
  {{ user.get_full_name }} followed by
{% endblock title %}

{% block content %}

  <div class="col">
    <h2>{{ user.get_full_name }} followed by</h2>
      <ul>
        {% for follow in followings %}
            <li><a href="{% url 'accounts:profile_detail' username=follow.followed.username %}">{{ follow.followed.get_full_name}}</a></li>

      {% empty %}
          -- no followers --
      {% endfor %}
      </ul>


  </div>

{% endblock content %}

templates/accounts/profile/followers.html
{% extends 'base/_base.html' %}

{% block title %}
  {{ user.get_full_name }} followed by
{% endblock title %}

{% block content %}

  <div class="col">
    <h2>{{ user.get_full_name }} followed by</h2>
      <ul>
        {% for follower in followers %}
            <li><a href="{% url 'accounts:profile_detail' username=follower.follower.username %}">{{ follower.follower.get_full_name }}</a></li>
      {% empty %}
          -- no followers --
      {% endfor %}
      </ul>


  </div>

{% endblock content %}

templates/accounts/profile/profile_create.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  Create profile {{ request.user.get_full_name }}
{% endblock title %}

{% block content %}

  <div class="col-3">
    <h2>Create profile {{ request.user.get_full_name }}</h2>

    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-info">Create</button>
    </form>
  </div>


{% endblock content %}

templates/accounts/profile/profile_detail.html
{% extends 'base/_base.html' %}
{% load profile_filters %}

{% block title %}
  Profile by {{ profile.user.username }}
{% endblock title %}


{% block content %}
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
            <div class="ms-4 d-flex flex-column" style="width: 150px;">
              <img src="{{ profile.avatar }}"
                alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                style="width: 170px; z-index: 1">
              {% if request.user == profile.user %}
                <button type="button" class="btn btn-outline-dark mt-4" data-mdb-ripple-color="dark"
                  style="z-index: 1;" id="btnEditProfile">
                  <a href="{% url 'accounts:profile_update' username=profile.user.username %}"
                     class="text-decoration-none text-dark">
                  Edit profile
                  </a>
                </button>
                <button type="button" class="btn btn-outline-dark mt-2" data-mdb-ripple-color="dark" id="btnChangePassword"
                  style="z-index: 1; width: 155px;">
                  <a href="{% url 'accounts:password_change' username=profile.user.username %}"
                     class="text-decoration-none text-dark">
                  Change password
                  </a>
                </button>
              {% endif %}
            </div>
            <div class="ms-3" style="margin-top: 70px;">
              <div class="mb-2">
                {% if request.user != profile.user and request.user.is_authenticated %}
                  {% if request.user|is_following:profile.user %}
                    <a href="{% url 'accounts:unfollow_user' username=profile.user.username %}">
                      <button class="btn btn-danger">Unfollow</button>
                    </a>
                  {% else %}
                    <a href="{% url 'accounts:follow_user' username=profile.user.username %}">
                      <button class="btn btn-info">Follow</button>
                    </a>
                  {% endif %}
                {% endif %}
              </div>
              <h5>
                {{ profile.user.first_name }} {{ profile.user.last_name }},
                {{ profile.date_of_birth|calculate_age }} years old
              </h5>
              <p>{{ profile.info }}</p>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-end text-center py-1">
              <div>
                <p class="mb-1 h5">{{ profile.user.posts.count }}</p>
                <p class="small text-muted mb-0">Posts</p>
              </div>
              <div class="px-3">
                <a href="{% url 'accounts:followers' username=profile.user.username %}" class="text-decoration-none">
                  <p class="mb-1 h5">{{ profile.user.followers.count }}</p>
                  <p class="small text-muted mb-0">Followers</p>
                </a>
              </div>
              <div>
                <a href="{% url 'accounts:following' username=profile.user.username %}" class="text-decoration-none">
                  <p class="mb-1 h5">{{ profile.user.following.count }}</p>
                  <p class="small text-muted mb-0">Following</p>
                </a>
              </div>
            </div>
          </div>

          {% block profile_content %}
          <div class="card-body p-4 mt-5 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4" style="background-color: #f8f9fa;">
                <p class="font-italic mb-1">{{ profile.bio|linebreaks }}</p>
              </div>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
              <p class="lead fw-normal mb-0">Recent posts photos</p>
              <p class="mb-0"><a href="#!" class="text-muted">Show all</a></p>
            </div>

            {% for post in posts %}
              {% if forloop.counter0|divisibleby:2 %}
              <div class="row g-2">
              {% endif %}
                <div class="col mb-2">
                  <a href="{{ post.get_absolute_url }}">
                    <img src="{{ post.image_url }}" alt="image 1" class="w-100 rounded-3">
                  </a>
                </div>
              {% if forloop.counter|divisibleby:2 or forloop.last %}
              </div>
              {% endif %}
            {% empty %}
            <h3>No posts yet</h3>
            {% endfor %}
          </div>
          {% endblock profile_content %}

        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/accounts/profile/profile_update.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  Update profile {{ request.user.get_full_name }}
{% endblock title %}

{% block content %}

  <div class="col-3">
    <h2>Update profile {{ request.user.get_full_name }}</h2>

    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-info">Update</button>
    </form>
  </div>

{% endblock content %}