accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'


urlpatterns = [
    # user account
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate/<str:username>/<str:token>/', views.activate_account_view, name='activate'),
    path('password_change/<str:username>/', views.change_password_view, name='password_change'),
    # user profile
    path('profile/create/', views.profile_create_view, name='profile_create'),
    path('profile/<str:username>/detail/', views.profile_detail_view, name='profile_detail'),
    path('profile/<str:username>/update/', views.profile_update_view, name='profile_update'),
    # user follow system
    path('profile/follow/<str:username>/', views.user_follow_view, name='follow_user'),
    path('profile/unfollow/<str:username>/', views.user_unfollow_view, name='unfollow_user'),
    path('profile/<str:username>/followers/', views.user_followers_view, name='followers'),
    path('profile/<str:username>/following/', views.user_following_view, name='following')
]

api/urls.py
from django.urls import path

from api.views import movies_views, accounts_views, posts_views

app_name = 'api'


urlpatterns = [
    # movies
    path('movies/movies/', movies_views.MovieListAPIView.as_view(), name='movies_list'),
    path('accounts/create/', accounts_views.UserCreateAPIView.as_view(), name='register'),
    path('accounts/activate/', accounts_views.ActivateUserAPIView.as_view(),name='activate'),
    path('posts/posts/', posts_views.PostsListAPIView.as_view(), name='posts_list'),
    path('posts/posts/<str:slug>/', posts_views.PostAPIView.as_view(), name='posts')
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'


urlpatterns = [
    path('', views.post_list_view, name='post_list'),
    path('post/<slug:post_slug>/', views.post_detail_view, name='post_detail'),
    path('post/<int:post_id>/like/', views.post_like_view, name='post_like'),
    path('post/<slug:slug>/comment/', views.post_comment_view, name='post_comment'),
    path('post/<int:post_id>/dislike/', views.post_dislike_view, name='post_dislike'),
    path('post/comment/<int:comment_id>/like/', views.comment_like_view, name='comment_like'),
    path('post/comment/<int:comment_id>/dislike/', views.comment_dislike_view, name='comment_dislike'),
    path('post/comment/disabling/<int:comment_id>/', views.comment_disable_view, name='comment_disabling'),
    path('post/comment/delete/<int:comment_id>', views.comment_delete_view, name='comment_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api/v1.0/', include('api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('weather/', include('weather.urls', namespace='weather')),
    path('', include('blog.urls', namespace='blog')),
]

api/views/posts_views.py
from rest_framework import status
from rest_framework.generics import get_object_or_404
from rest_framework.pagination import PageNumberPagination
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from blog.models import Post

from api.serializers.posts_serializers import PostListDetailReadSerializer, PostCreateUpdateSerializer


class PostsListAPIView(APIView):
    def get(self, request: Request) -> Response:
        posts = Post.objects.all()

        per_page = int(request.query_params.get('limit', 10))

        paginator = PageNumberPagination()
        paginator.page_size = per_page
        posts_page = paginator.paginate_queryset(posts, request)

        serializer = PostListDetailReadSerializer(posts_page, many=True)
        return Response(
            serializer.data,
            status=status.HTTP_200_OK
        )

    def post(self, request: Request) -> Response:
        create_serializer = PostCreateUpdateSerializer(data=request.data)
        if create_serializer.is_valid():
            post = create_serializer.save()
            read_serializer = PostListDetailReadSerializer(post)
            return Response(read_serializer.data, status=status.HTTP_201_CREATED)
        return Response(create_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PostAPIView(APIView):
    def get(self, request: Request, slug: str) -> Response:
        try:
            post = Post.objects.get(slug=slug)
            serializer = PostListDetailReadSerializer(post)
            return Response(
                serializer.data,
                status=status.HTTP_200_OK
            )
        except Post.DoesNotExist:
            return Response(
                {"status": "Not found."},
                status=status.HTTP_404_NOT_FOUND
            )

templates/blog/post/comment/comment_detail.html
{% load blog_filters %}

<div class="card mb-4" id="commentLike{{ comment.pk }}">
  <div class="card-body">
      {% if request.user.is_superuser %}
         <a href="{% url 'blog:comment_disabling' comment_id=comment.pk %}" class="text-decoration-none">
         {% if comment.active %}
            <button class="btn-sm btn-warning ms-auto">Disabled</button>
         {% else %}
            <button class="btn-sm btn-success ms-auto">Enabled</button>
         {% endif %}
        </a>
        <a href="{% url 'blog:comment_delete' comment_id=comment.pk %}" class="text-decoration-none">
          <button class="btn-sm btn-danger ms-auto">Delete</button>
        </a>
        <hr>
      {% endif %}

    <p class="small text-muted mb-2">{{ comment.created|timesince }}</p>

      <div class="d-flex flex-row align-items-center">
        {% if comment.active %}
          <p>{{ comment.body }}</p>
        {% else %}
            <p class="text-secondary"><i>Comment has been disabled by moderator</i></p>
        {% endif %} 
      </div>

    <div class="d-flex justify-content-between">
      <div class="d-flex flex-row align-items-center">
          <i class="fas fa-user mx-1"></i>
          <p class="small mb-0 ms-2"><a href="{% url 'accounts:profile_detail' username=comment.author.username %}">@{{ comment.author.get_full_name }}</a></p>
      </div>

      <div class="d-flex justify-content-end">
        <div class="d-flex flex-row align-items-center text-primary me-3">
          {% if comment|is_liked_by:request.user %}
            <p class="small mb-0">Unlike</p>
            <a href="{% url 'blog:comment_like' comment_id=comment.pk %}">
              <i class="fa-solid fa-thumbs-up ms-2 me-2" style="margin-top: -0.16rem;"></i>
            </a>
          {% else %}
            <p class="small mb-0">Like</p>
            <a href="{% url 'blog:comment_like' comment_id=comment.pk %}">
              <i class="fa-regular fa-thumbs-up ms-2 me-2" style="margin-top: -0.16rem;"></i>
            </a>
          {% endif %}
          <p class="small mb-0">{{ comment.likes_count }}</p>
        </div>

        <div class="d-flex flex-row align-items-center text-primary">
          {% if comment|is_disliked_by:request.user %}
            <p class="small mb-0">Undislike</p>
            <a href="{% url 'blog:comment_dislike' comment_id=comment.pk %}">
              <i class="fa-solid fa-thumbs-down ms-2 me-2" style="margin-top: -0.16rem;"></i>
            </a>
          {% else %}
            <p class="small mb-0">Dislike</p>
            <a href="{% url 'blog:comment_dislike' comment_id=comment.pk %}">
              <i class="fa-regular fa-thumbs-down ms-2 me-2" style="margin-top: -0.16rem;"></i>
            </a>
          {% endif %}
          <p class="small mb-0">{{ comment.dislikes_count }}</p>
        </div>
      </div>
    </div>
  </div>
</div>