accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'


urlpatterns = [
    # user account
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate/<str:username>/<str:token>/', views.activate_account_view, name='activate'),
    path('password_change/<str:username>/', views.change_password_view, name='password_change'),
    # user profile
    path('profile/create/', views.profile_create_view, name='profile_create'),
    path('profile/<str:username>/detail/', views.profile_detail_view, name='profile_detail'),
    path('profile/<str:username>/update/', views.profile_update_view, name='profile_update'),
    # user follow system
    path('profile/follow/<str:username>/', views.user_follow_view, name='follow_user'),
    path('profile/unfollow/<str:username>/', views.user_unfollow_view, name='unfollow_user'),
    path('profile/<str:username>/followers/', views.user_followers_view, name='followers'),
    path('profile/<str:username>/following/', views.user_following_view, name='following')
]

api/urls.py
from django.urls import path

from api.views import movies_views, accounts_views, posts_views

app_name = 'api'


urlpatterns = [
    # movies
    path('movies/movies/', movies_views.MovieListAPIView.as_view(), name='movies_list'),
    path('accounts/create/', accounts_views.UserCreateAPIView.as_view(), name='register'),
    path('accounts/activate/', accounts_views.ActivateUserAPIView.as_view(),name='activate'),
    path('posts/posts/', posts_views.PostsListAPIView.as_view(), name='posts_list'),
    path('posts/posts/<str:slug>/', posts_views.PostAPIView.as_view(), name='posts')
]

blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'


urlpatterns = [
    path('', views.post_list_view, name='post_list'),
    path('post/<slug:post_slug>/', views.post_detail_view, name='post_detail'),
    path('post/<int:post_id>/like/', views.post_like_view, name='post_like'),
    path('post/<slug:slug>/comment/', views.post_comment_view, name='post_comment'),
    path('post/<int:post_id>/dislike/', views.post_dislike_view, name='post_dislike'),
    path('post/comment/<int:comment_id>/like/', views.comment_like_view, name='comment_like'),
    path('post/comment/<int:comment_id>/dislike/', views.comment_dislike_view, name='comment_dislike'),
    path('post/comment/disabling/<int:comment_id>/', views.comment_disable_view, name='comment_disabling'),
    path('post/comment/delete/<int:comment_id>', views.comment_delete_view, name='comment_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api/v1.0/', include('api.urls', namespace='api')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('weather/', include('weather.urls', namespace='weather')),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.urls import reverse
from taggit.managers import TaggableManager
from django.db import models
from django.utils import timezone

from blog.managers import PublishedManager

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts')
    body = models.TextField(verbose_name='Content')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image_url = models.URLField(max_length=250, null=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='posts')
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-created', '-updated')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.slug])

    def likes_count(self):
        return self.likes.count()

    def dislikes_count(self):
        return self.dislikes.count()

    def is_liked_by(self, user):
        return self.likes.filter(user=user).exists()

    def is_disliked_by(self, user):
        return self.dislikes.filter(user=user).exists()


class PostLike(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_likes')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f'{self.user} on post {self.post.title}'


class PostDislike(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='dislikes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_dislikes')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f'{self.user} on post {self.post.title}'


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Comment by {self.author} - {self.body}'

    def likes_count(self):
        return self.likes.count()

    def dislikes_count(self):
        return self.dislikes.count()

    def is_liked_by(self, user):
        return self.likes.filter(user=user).exists()

    def is_disliked_by(self, user):
        return self.dislikes.filter(user=user).exists()


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_likes')

    class Meta:
        unique_together = ('comment', 'user')

    def __str__(self):
        return f'{self.user} like on comment {self.comment.body}'


class CommentDislike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='dislikes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_dislikes')

    class Meta:
        unique_together = ('comment', 'user')

    def __str__(self):
        return f'{self.user} dislike on comment {self.comment.body}'


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    followed = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('follower', 'followed')

    def __str__(self):
        return f"{self.follower} follows {self.followed}"

blog/forms.py
from django import forms

from blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

        widgets = {
            'body': forms.Textarea(attrs={
                'placeholder': 'Share your thoughts in the comments...',
                'rows': 4
            })
        }

        labels = {
            'body': 'Add your comment'
        }

api/views/posts_views.py
from rest_framework import status
from rest_framework.generics import get_object_or_404
from rest_framework.pagination import PageNumberPagination
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from blog.models import Post

from api.serializers.posts_serializers import PostListDetailReadSerializer, PostCreateUpdateSerializer


class PostsListAPIView(APIView):
    def get(self, request: Request) -> Response:
        posts = Post.objects.all()

        per_page = int(request.query_params.get('limit', 10))

        paginator = PageNumberPagination()
        paginator.page_size = per_page
        posts_page = paginator.paginate_queryset(posts, request)

        serializer = PostListDetailReadSerializer(posts_page, many=True)
        return Response(
            serializer.data,
            status=status.HTTP_200_OK
        )

    def post(self, request: Request) -> Response:
        create_serializer = PostCreateUpdateSerializer(data=request.data)
        if create_serializer.is_valid():
            post = create_serializer.save()
            read_serializer = PostListDetailReadSerializer(post)
            return Response(read_serializer.data, status=status.HTTP_201_CREATED)
        return Response(create_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PostAPIView(APIView):
    def get(self, request: Request, slug: str) -> Response:
        try:
            post = Post.objects.get(slug=slug)
            serializer = PostListDetailReadSerializer(post)
            return Response(
                serializer.data,
                status=status.HTTP_200_OK
            )
        except Post.DoesNotExist:
            return Response(
                {"status": "Not found."},
                status=status.HTTP_404_NOT_FOUND
            )

blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_http_methods

from blog import models
from blog import forms


def post_list_view(request: HttpRequest) -> HttpResponse:
    posts = models.Post.published.all()
    return render(request, 'blog/post/post_list.html', {'posts': posts})


def post_detail_view(request: HttpRequest, post_slug: str) -> HttpResponse:
    post = get_object_or_404(models.Post, slug=post_slug)
    form = forms.CommentForm()
    contex = {
        'post': post,
        'form': form
    }
    return render(request, 'blog/post/post_detail.html', contex)\


@login_required
@require_http_methods(["POST",])
def post_comment_view(request, slug):
    post = get_object_or_404(models.Post,
                             slug=slug,
                             status='published')
    comment = None
    user = request.user
    form = forms.CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = user
        comment.save()
        messages.success(request,'Your comment add')
    return HttpResponseRedirect(f'{post.get_absolute_url()}#postFooter')


@login_required
def post_like_view(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(models.Post, pk=post_id)

    if post.is_liked_by(request.user):
        like = post.likes.get(user=request.user)
        like.delete()
    else:
        models.PostLike.objects.create(post=post, user=request.user)
        if post.is_disliked_by(request.user):
            dislike = post.dislikes.get(user=request.user)
            dislike.delete()

    return HttpResponseRedirect(f'{post.get_absolute_url()}#postFooter')


@login_required
def post_dislike_view(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(models.Post, pk=post_id)

    if post.is_disliked_by(request.user):
        dislike = post.dislikes.get(user=request.user)
        dislike.delete()
    else:
        models.PostDislike.objects.create(post=post, user=request.user)
        if post.is_liked_by(request.user):
            like = post.likes.get(user=request.user)
            like.delete()

    return HttpResponseRedirect(f'{post.get_absolute_url()}#postFooter')


@login_required
def comment_like_view(request: HttpRequest, comment_id: int) -> HttpResponse:
    comment = get_object_or_404(models.Comment, pk=comment_id)

    if comment.is_liked_by(request.user):
        like = comment.likes.get(user=request.user)
        like.delete()
    else:
        models.CommentLike.objects.create(comment=comment, user=request.user)
        if comment.is_disliked_by(request.user):
            dislike = comment.dislikes.get(user=request.user)
            dislike.delete()

    return HttpResponseRedirect(f'{comment.post.get_absolute_url()}#commentLike{comment.pk}')


@login_required
def comment_dislike_view(request: HttpRequest, comment_id: int) -> HttpResponse:
    comment = get_object_or_404(models.Comment, pk=comment_id)

    if comment.is_disliked_by(request.user):
        dislike = comment.dislikes.get(user=request.user)
        dislike.delete()
    else:
        models.CommentDislike.objects.create(comment=comment, user=request.user)
        if comment.is_liked_by(request.user):
            like = comment.likes.get(user=request.user)
            like.delete()

    return HttpResponseRedirect(f'{comment.post.get_absolute_url()}#commentLike{comment.pk}')


def comment_disable_view(request, comment_id):
    comment = models.Comment.objects.get(pk=comment_id)
    if comment.active:
        comment.active=False
    else:
        comment.active = True
    comment.save()
    return HttpResponseRedirect(f'{comment.post.get_absolute_url()}#commentLike{comment.pk}')


@login_required
def comment_delete_view(request, comment_id):
    comment = models.Comment.objects.get(pk=comment_id)
    comment.delete()
    return HttpResponseRedirect(f'{comment.post.get_absolute_url()}#commentLike{comment.pk}')

templates/blog/post/post_detail.html
{% extends 'base/_base.html'%}
{% load static %}
{% load blog_filters %}
{% load crispy_forms_filters %}

{% block title %}
  Detail: {{ post.title }}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-10">
        <div class="col-md-8 mx-auto mt-5">
            <h1 class="mb-4">{{ post.title }}</h1>
        </div>
        <div class="text-center">
            <img src="{{ post.image_url }}" alt="" class="img-fluid mx-auto d-block mb-3">
        </div>

      <div class="card mb-4">
        <div class="card-body">
          <p class="card-text">
            <span>{{ post.body|linebreaks }}</span>
          </p>
        </div>
        <div class="card-footer text-muted d-flex justify-content-between align-items-center">
          <p class="mb-0">
              <i class="fas fa-user mx-1"></i>
              <a href="{% url 'accounts:profile_detail' username=post.author.username %}">@{{ post.author.get_full_name }}</a>
            - {{ post.updated|date:"l d M Y" }}
          </p>
          <div class="d-flex align-items-center ml-auto" id="postFooter">
              {# Post likes #}
              <div class="d-flex flex-row align-items-center text-primary">
                {% if post|is_liked_by:request.user %}
                  <p class="small mb-0">Unlike</p>
                  <a href="{% url 'blog:post_like' post_id=post.pk %}">
                    <i class="fa-solid fa-thumbs-up ms-2 me-2" style="margin-top: -0.16rem;"></i>
                  </a>
                {% else %}
                  <p class="small mb-0">Like</p>
                  <a href="{% url 'blog:post_like' post_id=post.pk %}">
                    <i class="fa-regular fa-thumbs-up ms-2 me-2" style="margin-top: -0.16rem;"></i>
                  </a>
                {% endif %}
                <p class="small mb-0">{{ post.likes_count }}</p>
              </div>
              {# Post dislikes #}
              <div class="d-flex flex-row align-items-center text-primary ms-2">
                {% if post|is_disliked_by:request.user %}
                  <p class="small mb-0">Undislike</p>
                  <a href="{% url 'blog:post_dislike' post_id=post.pk %}">
                    <i class="fa-solid fa-thumbs-down ms-2 me-2" style="margin-top: -0.16rem;"></i>
                  </a>
                {% else %}
                  <p class="small mb-0">Dislike</p>
                  <a href="{% url 'blog:post_dislike' post_id=post.pk %}">
                    <i class="fa-regular fa-thumbs-down ms-2 me-2" style="margin-top: -0.16rem;"></i>
                  </a>
                {% endif %}
                <p class="small mb-0">{{ post.dislikes_count }}</p>
              </div>
          </div>
        </div>
    </div>
</div>

    <div class="row d-flex justify-content-center">
      <div class="col-md-8 col-lg-6">
        <h1>Comments</h1>
        <div class="card shadow-0 border" style="background-color: #f0f2f5;">
          <div class="card-body p-4">
            <div class="form-outline mb-4" id="comments">
              <form action="{% url 'blog:post_comment' slug=post.slug %}"  method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-info mt-2">Add</button>
              </form>
            </div>
            <hr>
            {% for comment in post.comments.all %}
              {% include 'blog/post/comment/comment_detail.html' %}
            {% empty %}
              <h4>No comments yet</h4>
            {% endfor %}
            <hr>
            </div>
        </div>
      </div>
    </div>
</div>
    <script src="{% static 'js/scroll.js' %}"></script>
{% endblock %}

templates/blog/post/post_list.html
{% extends 'base/_base.html' %}

{% block title %}
  Posts list
{% endblock %}


{% block content %}
<div class="row mb-2">
    {% for post in posts %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">{{ post.category|capfirst }}</strong>
          <h3 class="mb-0">{{ post.title }}</h3>
          <div class="mb-1 text-muted">{{ post.publish|timesince }}</div>
          <p class="card-text mb-auto">{{ post.body|truncatewords:15 }}</p>
          <a href="{{ post.get_absolute_url }}" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="{{ post.image_url }}" width="300" height="200" alt="post image">
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
{% endblock %}